keqi000/proyek-pengembangan-web-berbasis-framework-terbaru

src/app/admin/generate_schedule/page.tsx
src/app/admin/home/page.tsx
src/app/admin/manage_lecturers/page.tsx
src/app/admin/manage_room/page.tsx

PR ini bertujuan untuk memperbaiki Type error pada beberapa halaman seperti `manage_room`, `manage_lecturer`, dan lain sebagainya.

fix: Fix typescript Type

---

src/app/admin/_component/Navbar.tsx
src/app/admin/layout.tsx

PR ini menambahkan perbedaan background pada navbar yang aktif
Berikut Screenshotnya:
Sebagai catatan, PR ini sedikit mengubah ukuran margin dan padding, jadi mohon memeriksa kembali layouting dari navbar yang sudah dibuat

feature: Set Active Navbar a bit different

---

package-lock.json
package.json
src/app/admin/_store/dosen.ts
src/app/admin/_store/jadwal.ts
src/app/admin/_store/ruangan.ts
src/app/admin/manage_lecturers/page.tsx

PR ini menambahkan fungsionalitas untuk menambahkan keterangan dosen pada UI.
PR ini menambah dependency baru yaitu `zustand`. Mohon tanggapan dan sarannya
P.S:
Karena PR ini menambah dependency baru, reviewer harus menjalankan `npm install` lagi agar dependency-nya dapat digunakan

feat: Add `dosen` basic state management

---

src/app/admin/layout.tsx

PR ini bertujuan untuk memperbaiki footer yang tidak terletak dibawah

fix: fix footer layout

---

src/app/admin/admin_component/Navbar.tsx
src/app/user/_component/navbar.tsx

Update navbar admin dan user
Copied from https://github.com/keqi000/proyek-pengembangan-web-berbasis-framework-terbaru/pull/28#issue-2952456540
Mohon @keqi000 untuk konfirmasinya, apakah ini sesuai

feature: Update navbar admin dan user

---

package-lock.json
package.json

PR ini bertujuan untuk menambah dependency `zod` untuk mempermudah validasi. Harap gunakan `npm install `agar dapat terinstall

feature: Add `zod` dependency

---

src/app/admin/_store/matakuliah.ts
src/app/admin/manage_subject/page.tsx

menambah halaman manage_subject dan storenya
Close #25

feature: Buat halaman mata kuliah

---

src/app/admin/_store/dosen.ts
src/app/admin/manage_lecturers/page.tsx

mengupdate halaman dosen agar tidak lagi menginput mata kuliah dan memperbaiki storenya

feature: Update halaman dosen

---

src/app/user/_component/Footer.tsx
src/app/user/layout.tsx

PR ini bertujuan untuk membuat route yang tepat pada link bagian footer pada halaman user. PR ini juga membuat bagian Footer menjadi komponen tersendiri untuk mempermudah dalam refactor

fix: Fix nonexistent route at user page

---

.github/workflows/pull-request.yml

PR ini menambah CI untuk memeriksa kode (lint) dan juga build
CLose #10

feat: Add linting and build check when push and pull request

---

src/app/admin/_store/jadwal.ts
src/app/admin/generate_schedule/page.tsx
src/app/admin/lecturers/page.tsx
src/app/admin/manage_subject/page.tsx
src/app/admin/rooms/page.tsx
src/app/signin/page.tsx
src/app/user/_component/navbar.tsx
src/app/user/cetak_jadwal/page.tsx
src/app/user/schedule/page.tsx

PR ini hanya menyelesaikan masalah-masalah lint pada commit sebelumnya

cleanup: fix lint issue

---

src/app/admin/settings/page.tsx

PR ini hanya menghapus `Lock` pada saat dari `lucide-react`

cleanup: fix lint issue from previous commit

---

src/app/admin/_scheme/course.ts
src/app/admin/_scheme/lecturers.ts
src/app/admin/_scheme/room.ts
src/app/admin/lecturers/page.tsx
src/app/admin/manage_subject/page.tsx
src/app/admin/rooms/page.tsx

PR ini membuat tipe-tipe data yang dibutuhkan berdasarkan zod schema. Hal ini dilakukan agar memudahkan untuk proses validasi data

cleanup: Set type declaration based on zod schema

---

src/app/admin/admin_component/Navbar.tsx

PR ini bertujuan untuk memperbaiki bug, logout tidak terlalu kelihatan saat scroll (karena overflow)

fix: fix the layout to ensure the logout button appeared when scrolling

---

src/app/admin/manage_subject/page.tsx
src/app/admin/rooms/page.tsx
src/app/admin/settings/page.tsx

PR ini memperbaiki warna teks yang ada pada beberapa halaman (seperti pada halaman settings) yang tidak memiliki kontras yang baik

fix: fix input color

---

src/app/admin/lecturers/page.tsx
src/app/admin/manage_subject/page.tsx
src/app/admin/rooms/page.tsx

PR ini mengubah tampilan search input agar terlihat lebih sesuai pada desktop namun dapat sesuai juga pada perangkat mobile.
Berikut salah satu screenshot-nya
---
Mobile
---
Desktop

fix: fix search input layout

---

src/app/signin/page.tsx

PR ini bertujuan untuk memperbaiki responsivitas pada tampilan mobile pada halaman Sign-in. Berikut Screenshotnya
---
Mobile
----
Desktop

fix: fix sign-in responsive in mobile layout

---

src/app/page.tsx

PR ini bertujuan untuk membuat halaman Sign Up Responsif pada tampilan mobile
Screenshot:
---
Mobile
---
Desktop

fix: fix sign-up mobile responsive

---

src/app/admin/generate_schedule/page.tsx
src/app/admin/manage_subject/page.tsx

menambah pemilihan dosen di halaman mata kuliah dan menyesuaikannya ke halaman generate schedule

updata halaman matakuliah dan generate schedule

---

src/app/admin/error.tsx
src/app/admin/help/page.tsx
src/app/admin/loading.tsx
src/app/admin/loading/page.tsx
src/app/admin/produk/[id]/page.tsx
src/app/admin/produk/not-found.tsx
src/app/admin/test-error/page.tsx

Tambah Error dan Loadind. (Keseringan Error dan Loading Jadi Ui Nya Gitu, LOL)

Add new fitur he hp

---

src/app/admin/generate_schedule/page.tsx

PR ini menyesuaikan besar konten yang ada pada layar desktop (agar tidak terlalu kecil), namun tetap responsif dalam tampilan mobile. Mohon bantuannya @keqi000 untuk periksa, siapa tahu ada yang kurang

fix: fix generate schedule layout in desktop

---

src/app/admin/layout.tsx

PR ini mengatur kembali posisi dari profile menu dan hamburger menu

fix: fix the position of hamburger menu and profile icon

---

src/app/admin/generate_schedule/page.tsx

PR ini membuat font yang lebih kecil pada `manage_schedule`

fix: set smaller font in GeneralJadwal's table

---

README.md

PR ini menambah dokumentasi mengenai aplikasi dan cara membuild aplikasi

documentation: Add about the app and how to build app

---

src/app/admin/generate_schedule/page.tsx
src/app/admin/home/page.tsx
src/app/admin/layout.tsx
src/app/admin/notifications/page.tsx
src/app/services/api.ts

This PR is used to cleanup the lint issue from previous commit

fix: Fix lint from previous commit

---

src/app/services/auth.ts
src/app/signin/page.tsx
src/app/signup/page.tsx

This PR change from `name` to `username` for `Sign-in` page.

fix: Set to Username at UI

---

package-lock.json
package.json

This is PR add `@tanstack/react-query` as dependency to be installed. Please use `npm install` again to ensure the new dependencies are installed

dep: Add `react-query`

---

src/app/admin/_hook/auth.ts
src/app/admin/manage_subject/page.tsx
src/app/layout.tsx
src/app/provider.tsx
src/app/services/auth.ts
src/app/signin/page.tsx
src/app/signup/page.tsx

This PR add integration for login and register endpoint

feat: integrate login and register endpoint

---

src/app/admin/_hook/auth.ts
src/app/services/auth.ts
src/app/signup/page.tsx

This PR fix the redirection problem using `redirect` (which not work in client). This PR change the redirection code using `useRouter`

fix: Fix Signup redirection to signin

---

src/app/admin/home/page.tsx
src/app/services/dashboard.ts
src/app/services/studentSchedule.ts
src/app/signin/page.tsx
src/app/user/cetak_jadwal/page.tsx
src/app/user/course/page.tsx
src/app/user/home/page.tsx

This PR will fix the lint issue that cause build error

fix: lint issue
